In [ ]:
#pip install fastf1

In [1]:
import fastf1

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
try: 
    fastf1.Cache.enable_cache(sys.path[0]+"/fastf1_cache")
except:
    os.makedirs(sys.path[0]+"/fastf1_cache")
    fastf1.Cache.enable_cache(sys.path[0]+"/fastf1_cache")

In [ ]:
#collecting weather data for each qualifying session
weather = pd.DataFrame()

In [ ]:
#collecting data by year to avoid rate limit errors
for i in range(1, 22):
    try:
        session = fastf1.get_session(2019, i, 'Qualifying')
        session.load()
        data = session.weather_data
        temp = {
            'session_id': '2019_' + str(i),
            'season': 2019,
            'Avg_AirTemp': data['AirTemp'].mean(),
            'Avg_Humidity': data['Humidity'].mean(),
            'Avg_Pressure': data['Pressure'].mean(),
            'Rainfall': data['Rainfall'].mean(),
            'Avg_TrackTemp': data['TrackTemp'].mean(),
            'Avg_WindSpeed': data['WindSpeed'].mean(),
        }
    
        weather = pd.concat([weather, pd.DataFrame([temp])], ignore_index=True)
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 18):
    try:
        session = fastf1.get_session(2020, i, 'Qualifying')
        session.load()
        data = session.weather_data
        temp = {
            'session_id': '2020_' + str(i),
            'season': 2020,
            'Avg_AirTemp': data['AirTemp'].mean(),
            'Avg_Humidity': data['Humidity'].mean(),
            'Avg_Pressure': data['Pressure'].mean(),
            'Rainfall': data['Rainfall'].mean(),
            'Avg_TrackTemp': data['TrackTemp'].mean(),
            'Avg_WindSpeed': data['WindSpeed'].mean(),
        }
    
        weather = pd.concat([weather, pd.DataFrame([temp])], ignore_index=True)
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 23):
    try:
        session = fastf1.get_session(2021, i, 'Qualifying')
        session.load()
        data = session.weather_data
        temp = {
            'session_id': '2021_' + str(i),
            'season': 2021,
            'Avg_AirTemp': data['AirTemp'].mean(),
            'Avg_Humidity': data['Humidity'].mean(),
            'Avg_Pressure': data['Pressure'].mean(),
            'Rainfall': data['Rainfall'].mean(),
            'Avg_TrackTemp': data['TrackTemp'].mean(),
            'Avg_WindSpeed': data['WindSpeed'].mean(),
        }
    
        weather = pd.concat([weather, pd.DataFrame([temp])], ignore_index=True)
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 23):
    try:
        session = fastf1.get_session(2022, i, 'Qualifying')
        session.load()
        data = session.weather_data
        temp = {
            'session_id': '2022_' + str(i),
            'season': 2022,
            'Avg_AirTemp': data['AirTemp'].mean(),
            'Avg_Humidity': data['Humidity'].mean(),
            'Avg_Pressure': data['Pressure'].mean(),
            'Rainfall': data['Rainfall'].mean(),
            'Avg_TrackTemp': data['TrackTemp'].mean(),
            'Avg_WindSpeed': data['WindSpeed'].mean(),
        }
    
        weather = pd.concat([weather, pd.DataFrame([temp])], ignore_index=True)
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 23):
    try:
        session = fastf1.get_session(2023, i, 'Qualifying')
        session.load()
        data = session.weather_data
        temp = {
            'session_id': '2023_' + str(i),
            'season': 2023,
            'Avg_AirTemp': data['AirTemp'].mean(),
            'Avg_Humidity': data['Humidity'].mean(),
            'Avg_Pressure': data['Pressure'].mean(),
            'Rainfall': data['Rainfall'].mean(),
            'Avg_TrackTemp': data['TrackTemp'].mean(),
            'Avg_WindSpeed': data['WindSpeed'].mean(),
        }
    
        weather = pd.concat([weather, pd.DataFrame([temp])], ignore_index=True)
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 25):
    try:
        session = fastf1.get_session(2024, i, 'Qualifying')
        session.load()
        data = session.weather_data
        temp = {
            'session_id': '2024_' + str(i),
            'season': 2024,
            'Avg_AirTemp': data['AirTemp'].mean(),
            'Avg_Humidity': data['Humidity'].mean(),
            'Avg_Pressure': data['Pressure'].mean(),
            'Rainfall': data['Rainfall'].mean(),
            'Avg_TrackTemp': data['TrackTemp'].mean(),
            'Avg_WindSpeed': data['WindSpeed'].mean(),
        }
    
        weather = pd.concat([weather, pd.DataFrame([temp])], ignore_index=True)
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
#weather.to_csv("data/weather.csv", index=False)

In [ ]:
weather = pd.read_csv("data/weather.csv")
weather.head()

,session_id,season,Avg_AirTemp,Avg_Humidity,Avg_Pressure,Rainfall,Avg_TrackTemp,Avg_WindSpeed
0,2019_1,2019,23.169231,69.102564,1016.680769,0.000000,37.770513,1.626923
1,2019_2,2019,25.088462,53.832051,1010.248718,0.025641,28.982051,1.530769
2,2019_3,2019,20.570886,48.420253,1015.783544,0.000000,33.964557,1.243038
3,2019_4,2019,15.898485,72.200000,1023.359848,0.000000,31.925758,1.062121
4,2019_5,2019,21.070130,58.271429,1004.596104,0.000000,33.800000,2.198701

In [5]:
weather.shape

(128, 8)

In [ ]:
#collecting car telemetry data for each qualifying session per driver
car_data = pd.DataFrame()

In [ ]:
for year in range(2019, 2025):
    for i in range(1, 25):
        try:
            session = fastf1.get_session(year, i, 'Qualifying')
            session.load()
            for driver in session.drivers:
                try:
                    data = session.car_data[driver].add_distance()
                    driver_result = session.results[session.results['DriverNumber'] == driver]
                    team = driver_result['TeamName'][0]
                    position = driver_result['Position'][0]
            
                    temp = {
                        'Driver': driver,
                        'Team': team,
                        'session_id': str(year) + '_' + str(i),
                        'season': year,
                        'Avg_Speed': data['Speed'].mean(),
                        'Max_Speed': data['Speed'].max(),
                        'Avg_Throttle': data['Throttle'].mean(),
                        'Max_Throttle': data['Throttle'].max(),
                        'Avg_RPM': data['RPM'].mean(),
                        'DRS_Activations': data['DRS'].sum(),
                        'GearChanges': data['nGear'].nunique(),
                        'Quali_Position': position
                    }
            
                    car_data = pd.concat([car_data, pd.DataFrame([temp])], ignore_index=True)
                except Exception as e:
                    print(f"Skipping driver {driver} in {session_id}: {e}")
        except Exception as e:
            print(f"Failed to load data for round {i}: {e}")

In [ ]:
#car_data.to_csv("data/cardata.csv", index=False)

In [ ]:
car_data = pd.read_csv("data/cardata.csv")
car_data.head()

,Driver,Team,session_id,season,Avg_Speed,Max_Speed,Avg_Throttle,Max_Throttle,Avg_RPM,DRS_Activations,GearChanges,Quali_Position
0,44,Mercedes,2019_1,2019,72.362914,321.0,77.332428,104.0,4011.674540,159768,9,1.0
1,77,Mercedes,2019_1,2019,77.224164,322.0,63.533740,104.0,4572.853615,151482,9,2.0
2,5,Ferrari,2019_1,2019,64.468105,318.0,65.327970,104.0,3734.268023,142262,9,3.0
3,33,Red Bull Racing,2019_1,2019,68.294922,320.0,45.247477,104.0,3842.628273,136242,9,4.0
4,16,Ferrari,2019_1,2019,68.324947,321.0,72.722550,104.0,3959.783061,158382,9,5.0

In [7]:
car_data.shape

(2559, 12)

In [ ]:
#collecting lap time data for each qualifying session per driver
lap_data = pd.DataFrame()

In [ ]:
for year in range(2019, 2025):
    for i in range(1, 25):
        try:
            session = fastf1.get_session(year, i, 'Qualifying')
            session.load()
            for driver in session.drivers:
                try:
                    data = session.laps.pick_driver(driver)
            
                    avg_lap_time = data['LapTime'].mean()
                    avg_sector_1_time = data['Sector1Time'].mean()
                    avg_sector_2_time = data['Sector2Time'].mean()
                    avg_sector_3_time = data['Sector3Time'].mean()
                    
                    temp = {
                        'Driver': driver,
                        'session_id': str(year) + '_' + str(i),
                        'season': year,
                        'Avg_Lap_Time': avg_lap_time.total_seconds()if pd.notnull(avg_sector_1_time) else None,
                        'Avg_Sector_1_Time': avg_sector_1_time.total_seconds() if pd.notnull(avg_sector_1_time) else None,
                        'Avg_Sector_2_Time': avg_sector_2_time.total_seconds() if pd.notnull(avg_sector_2_time) else None,
                        'Avg_Sector_3_Time': avg_sector_3_time.total_seconds() if pd.notnull(avg_sector_3_time) else None
                    }
            
                    lap_data = pd.concat([lap_data, pd.DataFrame([temp])], ignore_index=True)
                except Exception as e:
                    print(f"Skipping driver {driver} in {session_id}: {e}")
        except Exception as e:
            print(f"Failed to load data for round {i}: {e}")

In [ ]:
#lap_data.to_csv("data/lapdata.csv", index=False)

In [ ]:
lap_data = pd.read_csv("data/lapdata.csv")

In [9]:
lap_data.head()

,Driver,session_id,season,Avg_Lap_Time,Avg_Sector_1_Time,Avg_Sector_2_Time,Avg_Sector_3_Time
0,44,2019_1,2019,99.887000,34.987722,26.688277,38.263285
1,77,2019_1,2019,102.112642,34.605052,26.578421,41.077666
2,5,2019_1,2019,102.006363,35.413562,26.630250,39.076916
3,33,2019_1,2019,99.378250,35.317647,27.301647,36.972250
4,16,2019_1,2019,98.392416,34.423823,26.681176,38.623153

In [10]:
lap_data.shape

(2559, 7)

In [17]:
merged_data = pd.merge(lap_data, car_data, on=['Driver', 'session_id', 'season'], how='inner')
merged_data.head()

,Driver,session_id,season,Avg_Lap_Time,Avg_Sector_1_Time,Avg_Sector_2_Time,Avg_Sector_3_Time,Team,Avg_Speed,Max_Speed,Avg_Throttle,Max_Throttle,Avg_RPM,DRS_Activations,GearChanges,Quali_Position
0,44,2019_1,2019,99.887000,34.987722,26.688277,38.263285,Mercedes,72.362914,321.0,77.332428,104.0,4011.674540,159768,9,1.0
1,77,2019_1,2019,102.112642,34.605052,26.578421,41.077666,Mercedes,77.224164,322.0,63.533740,104.0,4572.853615,151482,9,2.0
2,5,2019_1,2019,102.006363,35.413562,26.630250,39.076916,Ferrari,64.468105,318.0,65.327970,104.0,3734.268023,142262,9,3.0
3,33,2019_1,2019,99.378250,35.317647,27.301647,36.972250,Red Bull Racing,68.294922,320.0,45.247477,104.0,3842.628273,136242,9,4.0
4,16,2019_1,2019,98.392416,34.423823,26.681176,38.623153,Ferrari,68.324947,321.0,72.722550,104.0,3959.783061,158382,9,5.0

In [18]:
qualifying_data = pd.merge(merged_data, weather, on=['session_id', 'season'], how='inner')
qualifying_data.head()

,Driver,session_id,season,Avg_Lap_Time,Avg_Sector_1_Time,Avg_Sector_2_Time,Avg_Sector_3_Time,Team,Avg_Speed,Max_Speed,...,Avg_RPM,DRS_Activations,GearChanges,Quali_Position,Avg_AirTemp,Avg_Humidity,Avg_Pressure,Rainfall,Avg_TrackTemp,Avg_WindSpeed
0,44,2019_1,2019,99.887000,34.987722,26.688277,38.263285,Mercedes,72.362914,321.0,...,4011.674540,159768,9,1.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923
1,77,2019_1,2019,102.112642,34.605052,26.578421,41.077666,Mercedes,77.224164,322.0,...,4572.853615,151482,9,2.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923
2,5,2019_1,2019,102.006363,35.413562,26.630250,39.076916,Ferrari,64.468105,318.0,...,3734.268023,142262,9,3.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923
3,33,2019_1,2019,99.378250,35.317647,27.301647,36.972250,Red Bull Racing,68.294922,320.0,...,3842.628273,136242,9,4.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923
4,16,2019_1,2019,98.392416,34.423823,26.681176,38.623153,Ferrari,68.324947,321.0,...,3959.783061,158382,9,5.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923

In [ ]:
#collecting race results - final race position for each driver
race_results = pd.DataFrame()

In [ ]:
#race results are not in cached data -- collecting by year to avoid rate limit errors
for i in range(1, 22):
    try:
        session = fastf1.get_session(2019, i, 'Race')
        session.load()
        for driver in session.drivers:
            try:
                driver_result = session.results[session.results['DriverNumber'] == driver]
                    
                if not driver_result.empty:
                    final_position = driver_result['Position'].iloc[0] if pd.notnull(driver_result['Position'].iloc[0]) else None
                else:
                    final_position = None
                        
                temp = {
                    'Driver': driver,
                    'session_id': '2019_' + str(i),
                    'season': 2019,
                    'Final_Race_Position': final_position
                }
        
                race_results = pd.concat([race_results, pd.DataFrame([temp])], ignore_index=True)
            except Exception as e:
                print(f"Skipping driver {driver} in {session_id}: {e}")
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 18):
    try:
        session = fastf1.get_session(2020, i, 'Race')
        session.load()
        for driver in session.drivers:
            try:
                driver_result = session.results[session.results['DriverNumber'] == driver]
                    
                if not driver_result.empty:
                    final_position = driver_result['Position'].iloc[0] if pd.notnull(driver_result['Position'].iloc[0]) else None
                else:
                    final_position = None
                        
                temp = {
                    'Driver': driver,
                    'session_id': '2020_' + str(i),
                    'season': 2020,
                    'Final_Race_Position': final_position
                }
        
                race_results = pd.concat([race_results, pd.DataFrame([temp])], ignore_index=True)
            except Exception as e:
                print(f"Skipping driver {driver} in {session_id}: {e}")
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 23):
    try:
        session = fastf1.get_session(2021, i, 'Race')
        session.load()
        for driver in session.drivers:
            try:
                driver_result = session.results[session.results['DriverNumber'] == driver]
                    
                if not driver_result.empty:
                    final_position = driver_result['Position'].iloc[0] if pd.notnull(driver_result['Position'].iloc[0]) else None
                else:
                    final_position = None
                        
                temp = {
                    'Driver': driver,
                    'session_id': '2021_' + str(i),
                    'season': 2021,
                    'Final_Race_Position': final_position
                }
        
                race_results = pd.concat([race_results, pd.DataFrame([temp])], ignore_index=True)
            except Exception as e:
                print(f"Skipping driver {driver} in {session_id}: {e}")
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 23):
    try:
        session = fastf1.get_session(2022, i, 'Race')
        session.load()
        for driver in session.drivers:
            try:
                driver_result = session.results[session.results['DriverNumber'] == driver]
                    
                if not driver_result.empty:
                    final_position = driver_result['Position'].iloc[0] if pd.notnull(driver_result['Position'].iloc[0]) else None
                else:
                    final_position = None
                        
                temp = {
                    'Driver': driver,
                    'session_id': '2022_' + str(i),
                    'season': 2022,
                    'Final_Race_Position': final_position
                }
        
                race_results = pd.concat([race_results, pd.DataFrame([temp])], ignore_index=True)
            except Exception as e:
                print(f"Skipping driver {driver} in {session_id}: {e}")
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 23):
    try:
        session = fastf1.get_session(2023, i, 'Race')
        session.load()
        for driver in session.drivers:
            try:
                driver_result = session.results[session.results['DriverNumber'] == driver]
                    
                if not driver_result.empty:
                    final_position = driver_result['Position'].iloc[0] if pd.notnull(driver_result['Position'].iloc[0]) else None
                else:
                    final_position = None
                        
                temp = {
                    'Driver': driver,
                    'session_id': '2023_' + str(i),
                    'season': 2023,
                    'Final_Race_Position': final_position
                }
        
                race_results = pd.concat([race_results, pd.DataFrame([temp])], ignore_index=True)
            except Exception as e:
                print(f"Skipping driver {driver} in {session_id}: {e}")
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
for i in range(1, 25):
    try:
        session = fastf1.get_session(2024, i, 'Race')
        session.load()
        for driver in session.drivers:
            try:
                driver_result = session.results[session.results['DriverNumber'] == driver]
                    
                if not driver_result.empty:
                    final_position = driver_result['Position'].iloc[0] if pd.notnull(driver_result['Position'].iloc[0]) else None
                else:
                    final_position = None
                        
                temp = {
                    'Driver': driver,
                    'session_id': '2024_' + str(i),
                    'season': 2024,
                    'Final_Race_Position': final_position
                }
        
                race_results = pd.concat([race_results, pd.DataFrame([temp])], ignore_index=True)
            except Exception as e:
                print(f"Skipping driver {driver} in {session_id}: {e}")
    except Exception as e:
        print(f"Failed to load data for round {i}: {e}")

In [ ]:
race_results.to_csv("data/raceresults.csv", index=False)

In [47]:
race_results.head()

  Driver session_id  season  Final_Race_Position
0     77     2019_1    2019                  1.0
1     44     2019_1    2019                  2.0
2     33     2019_1    2019                  3.0
3      5     2019_1    2019                  4.0
4     16     2019_1    2019                  5.0

In [86]:
data = pd.merge(qualifying_data, race_results, on=['Driver', 'session_id', 'season'], how='left')
data.head()

,Driver,session_id,season,Avg_Lap_Time,Avg_Sector_1_Time,Avg_Sector_2_Time,Avg_Sector_3_Time,Team,Avg_Speed,Max_Speed,...,DRS_Activations,GearChanges,Quali_Position,Avg_AirTemp,Avg_Humidity,Avg_Pressure,Rainfall,Avg_TrackTemp,Avg_WindSpeed,Final_Race_Position
0,44,2019_1,2019,99.887000,34.987722,26.688277,38.263285,Mercedes,72.362914,321.0,...,159768,9,1.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923,2.0
1,77,2019_1,2019,102.112642,34.605052,26.578421,41.077666,Mercedes,77.224164,322.0,...,151482,9,2.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923,1.0
2,5,2019_1,2019,102.006363,35.413562,26.630250,39.076916,Ferrari,64.468105,318.0,...,142262,9,3.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923,4.0
3,33,2019_1,2019,99.378250,35.317647,27.301647,36.972250,Red Bull Racing,68.294922,320.0,...,136242,9,4.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923,3.0
4,16,2019_1,2019,98.392416,34.423823,26.681176,38.623153,Ferrari,68.324947,321.0,...,158382,9,5.0,23.169231,69.102564,1016.680769,0.0,37.770513,1.626923,5.0

In [87]:
data.shape

(2559, 23)

In [ ]:
#XGB Ranker model does not allow String data types
#one-hot encoding Team column
encoded_data = pd.get_dummies(data, columns=['Team'])
encoded_data.head()

,Driver,session_id,season,Avg_Lap_Time,Avg_Sector_1_Time,Avg_Sector_2_Time,Avg_Sector_3_Time,Avg_Speed,Max_Speed,Avg_Throttle,...,Team_Haas F1 Team,Team_Kick Sauber,Team_McLaren,Team_Mercedes,Team_RB,Team_Racing Point,Team_Red Bull Racing,Team_Renault,Team_Toro Rosso,Team_Williams
0,44,2019_1,2019,99.887000,34.987722,26.688277,38.263285,72.362914,321.0,77.332428,...,False,False,False,True,False,False,False,False,False,False
1,77,2019_1,2019,102.112642,34.605052,26.578421,41.077666,77.224164,322.0,63.533740,...,False,False,False,True,False,False,False,False,False,False
2,5,2019_1,2019,102.006363,35.413562,26.630250,39.076916,64.468105,318.0,65.327970,...,False,False,False,False,False,False,False,False,False,False
3,33,2019_1,2019,99.378250,35.317647,27.301647,36.972250,68.294922,320.0,45.247477,...,False,False,False,False,False,False,True,False,False,False
4,16,2019_1,2019,98.392416,34.423823,26.681176,38.623153,68.324947,321.0,72.722550,...,False,False,False,False,False,False,False,False,False,False

In [5]:
encoded_data.isnull().sum()

Driver                     0
session_id                 0
season                     0
Avg_Lap_Time              17
Avg_Sector_1_Time         10
Avg_Sector_2_Time          6
Avg_Sector_3_Time          8
Avg_Speed                  0
Max_Speed                  0
Avg_Throttle               0
Max_Throttle               0
Avg_RPM                    0
DRS_Activations            0
GearChanges                0
Quali_Position             3
Avg_AirTemp                0
Avg_Humidity               0
Avg_Pressure               0
Rainfall                   0
Avg_TrackTemp              0
Avg_WindSpeed              0
Final_Race_Position        3
Team_Alfa Romeo            0
Team_Alfa Romeo Racing     0
Team_AlphaTauri            0
Team_Alpine                0
Team_Aston Martin          0
Team_Ferrari               0
Team_Haas F1 Team          0
Team_Kick Sauber           0
Team_McLaren               0
Team_Mercedes              0
Team_RB                    0
Team_Racing Point          0
Team_Red Bull Racing       0
Team_Renault               0
Team_Toro Rosso            0
Team_Williams              0
dtype: int64

In [ ]:
#dropping null values
encoded_data = encoded_data.dropna(subset=['Avg_Lap_Time', 'Avg_Sector_1_Time', 'Avg_Sector_2_Time', 'Avg_Sector_3_Time', 'Quali_Position', 'Final_Race_Position'])

In [9]:
encoded_data.isnull().sum()

Driver                    0
session_id                0
season                    0
Avg_Lap_Time              0
Avg_Sector_1_Time         0
Avg_Sector_2_Time         0
Avg_Sector_3_Time         0
Avg_Speed                 0
Max_Speed                 0
Avg_Throttle              0
Max_Throttle              0
Avg_RPM                   0
DRS_Activations           0
GearChanges               0
Quali_Position            0
Avg_AirTemp               0
Avg_Humidity              0
Avg_Pressure              0
Rainfall                  0
Avg_TrackTemp             0
Avg_WindSpeed             0
Final_Race_Position       0
Team_Alfa Romeo           0
Team_Alfa Romeo Racing    0
Team_AlphaTauri           0
Team_Alpine               0
Team_Aston Martin         0
Team_Ferrari              0
Team_Haas F1 Team         0
Team_Kick Sauber          0
Team_McLaren              0
Team_Mercedes             0
Team_RB                   0
Team_Racing Point         0
Team_Red Bull Racing      0
Team_Renault              0
Team_Toro Rosso           0
Team_Williams             0
dtype: int64

In [10]:
encoded_data.shape

(2538, 38)

In [15]:
#renaming/combining columns based on team name changes and rebranding

#Alpha Tauri, Toro Rosso, and RB became Racing Bulls
encoded_data['Team_Racing Bulls'] = encoded_data[['Team_Toro Rosso', 'Team_AlphaTauri', 'Team_RB']].any(axis=1).astype(bool)
encoded_data.drop(columns=['Team_Toro Rosso', 'Team_AlphaTauri', 'Team_RB'], inplace=True)

#Alfa Romeo became Kick Sauber
encoded_data['Team_Sauber'] = encoded_data[['Team_Alfa Romeo', 'Team_Alfa Romeo Racing', 'Team_Kick Sauber']].any(axis=1).astype(bool)
encoded_data.drop(columns=['Team_Alfa Romeo', 'Team_Alfa Romeo Racing', 'Team_Kick Sauber'], inplace=True)
encoded_data.rename(columns={'Team_Sauber':'Team_Kick Sauber'}, inplace=True)

#Renault became Alpine
encoded_data['Team_Alp'] = encoded_data[['Team_Alpine', 'Team_Renault']].any(axis=1).astype(bool)
encoded_data.drop(columns=['Team_Alpine', 'Team_Renault'], inplace=True)
encoded_data.rename(columns={'Team_Alp':'Team_Alpine'}, inplace=True)

#Racing Point became Aston Martin
encoded_data['Team_Aston'] = encoded_data[['Team_Racing Point', 'Team_Aston Martin']].any(axis=1).astype(bool)
encoded_data.drop(columns=['Team_Racing Point', 'Team_Aston Martin'], inplace=True)
encoded_data.rename(columns={'Team_Aston':'Team_Aston Martin'}, inplace=True)

In [16]:
encoded_data.dtypes

Driver                    int64
session_id               object
season                    int64
Avg_Lap_Time            float64
Avg_Sector_1_Time       float64
Avg_Sector_2_Time       float64
Avg_Sector_3_Time       float64
Avg_Speed               float64
Max_Speed               float64
Avg_Throttle            float64
Max_Throttle            float64
Avg_RPM                 float64
DRS_Activations           int64
GearChanges               int64
Quali_Position          float64
Avg_AirTemp             float64
Avg_Humidity            float64
Avg_Pressure            float64
Rainfall                float64
Avg_TrackTemp           float64
Avg_WindSpeed           float64
Final_Race_Position     float64
Team_Ferrari               bool
Team_Haas F1 Team          bool
Team_McLaren               bool
Team_Mercedes              bool
Team_Red Bull Racing       bool
Team_Williams              bool
Team_Racing Bulls          bool
Team_Kick Sauber           bool
Team_Alpine                bool
Team_Aston Martin          bool
dtype: object

In [ ]:
#final dataset used for the model
encoded_data.to_csv("data/data.csv", index=False)